spring.application.name=echo

# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# JWT
jwt.secret=${JWT_SECRET:defaultSecretKeyForDevelopmentOnlyDoNotUseInProduction2025!}
jwt.expiration-ms=86400000
